# Python Full Stack Day 3

## Importing Libraries `numpy` `sys` `time`

In [1]:
import numpy as np
import sys
import time

## 1-D Array

In [2]:
a = np.array([5,1,2,4,3])
print(a)

[5 1 2 4 3]


## 2-D Array

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


## 3-D Array

In [4]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)

print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


## Attributes of `numpy`

In [5]:
a=np.array([1,2,3,4,5])
print(a)

print(a.ndim)
print(a.size)
print(a.dtype)

[1 2 3 4 5]
1
5
int64


## Numpy array dtype

- All elements are treated as strings because arrays can only contain elements of the same type.

In [6]:
a=np.array([1,2,3,'re']) 
print(a)
print(a.dtype)

['1' '2' '3' 're']
<U21


## Typecasting in numpy array

In [7]:
import numpy as np

a=np.array([1,4,5,6])
print(a, a.dtype)

b=a.astype('float64') #converting int to float
c=a.astype('<U21') #converting int to string

print(b, b.dtype)
print(c, c.dtype)

[1 4 5 6] int64
[1. 4. 5. 6.] float64
['1' '4' '5' '6'] <U21


## Numpy Array vs List - Performance

### Space Comparision

In [8]:
a=np.array([1,4,5,6])
print(a)

ele_size_array = a.itemsize
print(f"Element size in numpy array: {ele_size_array}")

array_size = a.size
print(f"Total size of numpy array: {array_size}")

total_array_size = ele_size_array * array_size
print(f"Total numpy array bit size is {total_array_size}")

b=[1,4,5,6]
print(b)

ele_size_list = sys.getsizeof(b)
print(f"Element size in list: {ele_size_list}")

list_size = len(b)
print(f"Total size of list: {list_size}")

total_list_size = ele_size_list * list_size
print(f"Total numpy array bit size is {total_list_size}")

[1 4 5 6]
Element size in numpy array: 8
Total size of numpy array: 4
Total numpy array bit size is 32
[1, 4, 5, 6]
Element size in list: 88
Total size of list: 4
Total numpy array bit size is 352


### Time Comparision

In [9]:
SIZE = 10

#declaring two lists with range
l1 = range(SIZE)
l2 = range(SIZE)

#delcaring array
arr1 = np.arange(SIZE)
arr2 = np.arange(SIZE)

#Time
initial_t = time.time()
print(f"Time: {initial_t}")

l3 = [(a*b) for a,b in zip(l1,l2)]
print(f"List multiplication time: {time.time()-initial_t}")
initial_t = time.time()

arr3 = arr2 * arr1
print(f"Multiplication of array: {time.time()-initial_t}")

Time: 1720179503.575391
List multiplication time: 0.0
Multiplication of array: 0.001007080078125


## Addition feature in numpy array

In [10]:
a = [45, 51, 96]
#a = a + 4  #In list it is not possible
print(a)

ar = np.array(a)
ar = ar + 9
print(ar)

[45, 51, 96]
[ 54  60 105]


## `linspace` and `random` functions in numpy

In [11]:
ab = np.linspace(1, 3, 5, endpoint=False, retstep=True)
print(ab)

b = np.random.random((4,3))
print(b)

(array([1. , 1.4, 1.8, 2.2, 2.6]), np.float64(0.4))
[[0.53617318 0.37747626 0.09245323]
 [0.98772987 0.06223268 0.46241188]
 [0.44452147 0.23721233 0.04121373]
 [0.08102842 0.09189385 0.76116631]]


## Array Slicing

In [12]:
a = [1, 2, 3, 4, 5, 6, 7]
b = np.array(a) #convert list to array

print(b)
type(b)

print(b[2:5])
print(b[:4])
print(b[-1:-3:-1])
print(b[-3:-1])
print(b[0:5:2])
print(b[2:5])
print(b[::2])

[1 2 3 4 5 6 7]
[3 4 5]
[1 2 3 4]
[7 6]
[5 6]
[1 3 5]
[3 4 5]
[1 3 5 7]


## 2-D and 3-D Arrays

In [13]:
print("2D-Array")
a = np.array(np.random.randint(10, 45,(6,2)))
print(a)

print("---------------------------------")

print("3D Array-2,1,6")
n = (2, 1, 6) #3D
print(np.reshape(a, n))

print("---------------------------------")

2D-Array
[[17 44]
 [43 19]
 [43 12]
 [10 33]
 [16 32]
 [34 14]]
---------------------------------
3D Array-2,1,6
[[[17 44 43 19 43 12]]

 [[10 33 16 32 34 14]]]
---------------------------------


## Reshape

In [14]:
print("3D Array-3,2,2")
n = (3, 2, 2)
print(np.reshape(a, n))

3D Array-3,2,2
[[[17 44]
  [43 19]]

 [[43 12]
  [10 33]]

 [[16 32]
  [34 14]]]


## Resize

In [15]:
a = np.array([[5,1], [4,5], [9,6]]) #2D Array

print(np.resize(a, (2,3)))
print("-----------------------")
print(np.resize(a, (1,4)))
print("-----------------------")
print(np.resize(a, (6,1)))

[[5 1 4]
 [5 9 6]]
-----------------------
[[5 1 4 5]]
-----------------------
[[5]
 [1]
 [4]
 [5]
 [9]
 [6]]


## `Flatten` method in numpy

In [16]:
a = np.array([[1,4,7], [2,5,8], [3,6,9]])
print(a)

print("---------------------------")

print(a.flatten())

print("---------------------------")

#Row Major
print(a.flatten('F'))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
---------------------------
[1 4 7 2 5 8 3 6 9]
---------------------------
[1 2 3 4 5 6 7 8 9]


## Matices in numpy

In [17]:
print(np.zeros((4,3)))
print(np.ones((3,5)))
print(np.identity(4))

#print 30 in 3x3
print(np.ones((3,3), dtype=int)*30)

#other way
print(np.random.randint(30,31,(3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]


## Copy and View Array

In [18]:
a = np.array([11,22,33,44,55])
print(a)

#copy array
b = a.copy()
print(b)

#replacing values
b[3] = 90
print(b)

[11 22 33 44 55]
[11 22 33 44 55]
[11 22 33 90 55]


## Inserting element in array

- **Syntax:** `insert(array, index, value, axis)`
    - axis - 0 for row
    - axis - 1 for column

In [19]:
a = np.array(np.random.randint(0,51,(1,10)))
print(a)

print(np.insert(a,4,51))

#for 2D array

a = np.array(np.random.randint(0,51,(3,3)))
print(np.insert(a,2,0,0)) #for whole row

a = np.array(np.random.randint(0,51,(3,3)))
print(np.insert(a,2,0,1)) #for whole column

[[38 10 44 17 36 49 36 44 11 38]]
[38 10 44 17 51 36 49 36 44 11 38]
[[11 38 12]
 [33 19 31]
 [ 0  0  0]
 [29 17 25]]
[[15 40  0  6]
 [33 31  0 32]
 [ 3 19  0 41]]


## Arithmetic operations in numpy

In [20]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

### Addition

In [21]:
print(np.add(arr1, arr2))

[30 32 34 36 38 40]


### Subtract

In [22]:
print(np.subtract(arr1, arr2))

[-10 -10 -10 -10 -10 -10]


### Multiply

In [23]:
print(np.multiply(arr1, arr2))

[200 231 264 299 336 375]


### Divide

In [24]:
print(np.divide(arr1, arr2))

[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]


### Sum

In [25]:
print(np.sum(arr1))
print(np.sum(arr1, axis=0))

75
75


### Min and Max

In [26]:
print(np.min(arr1))
print(np.max(arr1))

10
15


### Mean

In [27]:
print(np.mean(arr1))

12.5


### Sorting

In [28]:
print(np.sort(arr1)) #ascending
print(-np.sort(-arr1)) #decending

[10 11 12 13 14 15]
[15 14 13 12 11 10]
